package com.firmansyah.malangcamp.other

class ConstVariable {
    companion object {
        const val STATUS_PATH = "status"
        const val STOCK_PATH = "stock"
        const val DELETE_PATH = "delete"
        const val USERS_PATH = "users"
        const val KERANJANG_PATH = "keranjang"
        const val IS_PEGAWAI_PATH = "isPegawai"
        const val JUMLAH_PATH = "jumlah"
        const val FOTO_PROFIL_PATH = "fotoProfil"
        const val Username_PATH = "username"
        const val NAMA_DEPAN_PATH = "namaDepan"
        const val NAMA_BELAKANG_PATH = "namaBelakang"
        const val Email_PATH = "email"
        const val NO_TELP_PATH = "noTelp"
        const val GALLERY_IMAGE = "image/*"
        const val IMAGES_LOCATION = "images/"
        const val BUKTI_LOCATION = "bukti/"
        const val PROFIL_LOCATION = "profil/"
        const val BARANG = "barang"
        const val PEMBAYARAN = "pembayaran"
        const val DITOLAK = "ditolak"
        const val DITERIMA = "diterima"
        const val NETRAL = "netral"
        const val EXTRA_IMAGE = "extra_image"
        const val EXTRA_PEMBAYARAN = "extra_pembayaran"
        const val EXTRA_BARANG = "extra_barang"
        const val LIST_BOOKING_SCREEN_ROUTE = "listBookingScreen"
        const val LIST_BARANG_SCREEN_ROUTE = "listBarangScreen"
        const val BOOKING_DETAIL_SCREEN_ROUTE = "bookingDetailScreen"
        const val ADD_BARANG_SCREEN_ROUTE = "addBarangScreen"
        const val BARANG_DETAIL_SCREEN_ROUTE = "barangDetailScreen"
        const val LIST_BARANG_SEWA_SCREEN_ROUTE = "listBarangSewaScreen"
        const val PEMBAYARAN_SCREEN_ROUTE = "pembayaranScreen"
        const val RIWAYAT_PEMESANAN_SCREEN_ROUTE = "riwayatPemesananScreen"
        const val SEPATU = "Sepatu"
        const val JAKET = "Jaket"
        const val TAS = "Tas"
        const val SLEEPING_BAG = "Sleeping Bag"
        const val TENDA = "Tenda"
        const val BARANG_LAINNYA = "Barang Lainnya"
        const val RATING_PATH = "rating"
        const val DATE_FORMAT = "dd/MM/yyyy"
        const val TIME_FORMAT = "HH:mm"
        const val ID_BARANG_PATH = "idBarang"
        const val EXTRA_UID = "extra_uid"
    }
}